/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PropertyCard {
        /**
          * The property ID to display
          * @default '1'
         */
        "propertyId": string;
    }
}
declare global {
    interface HTMLPropertyCardElement extends Components.PropertyCard, HTMLStencilElement {
    }
    var HTMLPropertyCardElement: {
        prototype: HTMLPropertyCardElement;
        new (): HTMLPropertyCardElement;
    };
    interface HTMLElementTagNameMap {
        "property-card": HTMLPropertyCardElement;
    }
}
declare namespace LocalJSX {
    interface PropertyCard {
        /**
          * The property ID to display
          * @default '1'
         */
        "propertyId"?: string;
    }

    interface PropertyCardAttributes {
        "propertyId": string;
    }

    interface IntrinsicElements {
        "property-card": Omit<PropertyCard, keyof PropertyCardAttributes> & { [K in keyof PropertyCard & keyof PropertyCardAttributes]?: PropertyCard[K] } & { [K in keyof PropertyCard & keyof PropertyCardAttributes as `attr:${K}`]?: PropertyCardAttributes[K] } & { [K in keyof PropertyCard & keyof PropertyCardAttributes as `prop:${K}`]?: PropertyCard[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "property-card": LocalJSX.IntrinsicElements["property-card"] & JSXBase.HTMLAttributes<HTMLPropertyCardElement>;
        }
    }
}
